### ISSUE TITLE
send SMS with GPS coordinates

### ISSUE THREAD

**Issue by wolverineks** [SyntaxBlitz/PluckLock#22]
If the phone is stolen, having the GPS coordinates sent to a predetermined number at some intervals would aid in recovery.

Find my phone has a similar functionality.

FindMyPhone (Helps you find a mislaid phone) - https://f-droid.org/app/se.erikofsweden.findmyphone

This would also expand the apps user base to people who are injured, dropped their phone, and/or are unable to dial for help.

**Comment by SyntaxBlitz** [comment]
It's an interesting idea, but I think it is beyond the scope of the app. The goal of this app is to prevent people from getting use out of your phone if they've snatched it from you; it was inspired by a situation that arose in a high school cafeteria setting where a fellow student got a little too curious about what was on my phone.

If you've locked your phone, the only thing the thief can do with your phone is get at its filesystem or make emergency calls. A remote wipe would prevent filesystem access, of course, but you can already do this with other apps that were designed for this purpose.

What you're suggesting is an aid in actually finding the phone. You've even linked another app that can do this already. Personally, I don't really see why PluckLock needs to be a mega-application for anything involving a lost or stolen phone. In this case I'd rather stick to the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) of creating small, single-purposed programs (and maintaining extensibility by releasing source code) than trying to reinvent the wheel with a minor extra feature.

Realistically, this app was never quite designed for thieves taking your phone in the street, because they tend not to care about your personal files anyway (normally they'll just wipe and sell the phone on the street). It also was not designed for "people who are injured, dropped their phone, and/or are unable to dial for help", because the app's core concept (the pluck lock) is not suited to these use cases. I built the app to prevent students from quickly and forcefully taking my unlocked phone for nefarious means.

If you think you have a good, relevant idea that you'd like to pull request, feel free! I do love pull requests.
